CREATE TABLE TURNO (
    ID_TURNO AUTOINCREMENT PRIMARY KEY,
    TURNO TEXT (50)
);

CREATE TABLE TT (
    ID_TEMAS INTEGER PRIMARY KEY,
    N_TEMA TEXT (50)
);

CREATE TABLE SEXO (
    ID_S AUTOINCREMENT PRIMARY KEY,
    SEXO TEXT (10)
);

CREATE TABLE PERSONAL (
    ID_TRABAJADOR LONG NOT NULL,
    N_PLAZA LONG,
    C_PUESTO TEXT (10),
    N_COMPLETO TEXT (100),
    SEXO INTEGER,
    F_INGRESO DATETIME,
    F_EGRESO DATETIME,
    CURP TEXT (18),
    RFC TEXT (14),
    NIVEL INTEGER,
    TURNO INTEGER,
    PUESTO_FUNCIONAL TEXT (255),
    CONSTRAINT PK_ID_PERSONAL PRIMARY KEY (ID_TRABAJADOR),
    CONSTRAINT FK_ID_TURNO1 FOREIGN KEY (TURNO) REFERENCES TURNO (ID_TURNO),
    CONSTRAINT FK_ID_S1 FOREIGN KEY (SEXO) REFERENCES SEXO (ID_S)
);

CREATE TABLE SUPERVISORES (
    ID_SUP TEXT (10),
    ID_TRA LONG NOT NULL,
    CONTRASENA TEXT (10),
    ROL TEXT (50),
    CONSTRAINT PK_SUP PRIMARY KEY (ID_SUP),
    CONSTRAINT FK_TR3 FOREIGN KEY (ID_TRA) REFERENCES PERSONAL (ID_TRABAJADOR)
);

CREATE TABLE REGISTRO (
    ID_TT1 LONG NOT NULL,
    ID_TR2 LONG NOT NULL,
    FECHA DATETIME,
    CANT INTEGER,
    CONSTRAINT FK_TR2 FOREIGN KEY (ID_TR2) REFERENCES PERSONAL (ID_TRABAJADOR),
    CONSTRAINT FK_TT1 FOREIGN KEY (ID_TT1) REFERENCES TT (ID_TEMAS)
);